// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_TITLE;
lv_obj_t *ui_Label2;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void hello_tft_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );

 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}
static void anim_progress_load(void* obj, int32_t v) {
    lv_bar_set_start_value(obj, 0, LV_ANIM_ON);
    lv_bar_set_value(obj, v, LV_ANIM_ON);
}
void hello_tft2_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
    lv_anim_t anim;
    lv_anim_init(&anim);
 lv_anim_set_var(&anim,TargetObject);

lv_anim_set_exec_cb(&anim, anim_progress_load);
lv_anim_set_values(&anim, 0, 100);
lv_anim_set_path_cb(&anim, lv_anim_path_ease_in_out);
lv_anim_set_time(&anim, 800);
lv_anim_set_delay(&anim, delay);
lv_anim_start(&anim);

}
void hello_tft3_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );

lv_anim_start(&PropertyAnimation_0);

}
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_obj_set_style_opa(ui_Bar1, 0, 0);
lv_bar_set_value(ui_Bar1,0,LV_ANIM_ON);
lv_obj_set_width( ui_Bar1, 150);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
ui_TITLE = lv_label_create(ui_Screen1);
lv_obj_set_style_opa(ui_TITLE, 0, 0);
lv_obj_set_width( ui_TITLE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TITLE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TITLE, -24 );
lv_obj_set_y( ui_TITLE, -14 );
lv_obj_set_align( ui_TITLE, LV_ALIGN_CENTER );
lv_label_set_text(ui_TITLE,"DESIGN BY");
ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_style_opa(ui_Label2, 0, 0);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 51 );
lv_obj_set_y( ui_Label2, -14 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ZYC");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x1B9CFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
hello_tft_Animation( ui_Bar1, 500);
hello_tft_Animation( ui_TITLE, 500);
hello_tft_Animation( ui_Label2, 500);
hello_tft2_Animation(ui_Bar1, 1000);
hello_tft3_Animation( ui_Bar1, 2000);
hello_tft3_Animation( ui_TITLE, 2000);
hello_tft3_Animation( ui_Label2, 2000);
}
