// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project
#include "lvgl.h"
#include "mainPage.h"
#include "../lvgl_anim/lvgl_anim.h"
// SCREEN: ui_Screen1
extern lv_obj_t *ui_Screen1;
lv_obj_t* arc;
lv_obj_t* arc2;
lv_obj_t* arc3;
lv_obj_t* label1;
lv_obj_t* label2;
lv_obj_t* label3;

    static lv_style_t arc_style; //定义样式变量
        static lv_style_t arc_style2; //定义样式变量
lv_anim_timeline_t* start_mainPage_anim_timeline ;
void task2_cb(lv_timer_t * tmr)
{
	printf("ok\n");
}

static void set_arc_bg_angle(void* obj ,int32_t v)
{
    
    
    lv_arc_set_bg_angles(obj, 0, v);
}
static void set_arc_angle(void* obj ,int32_t v)
{  
   lv_arc_set_value(obj, v);
}

void mainPage_init(void)
{


    arc = lv_arc_create(ui_Screen1);
    lv_obj_set_style_arc_width( arc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_arc_width( arc, 15, LV_PART_MAIN );
    lv_obj_set_style_arc_color(arc,lv_color_hex(0x00425c),LV_PART_MAIN );

    lv_arc_set_bg_angles(arc, 0, 0);
   lv_arc_set_range(arc, 0, 100);
    lv_arc_set_value(arc, 0);
    lv_arc_set_rotation(arc, 90);
    lv_obj_set_size(arc, 220, 220);
    lv_obj_align(arc, LV_ALIGN_CENTER, 0, 0);
    
    
    
     arc2 = lv_arc_create(ui_Screen1);
    lv_obj_set_style_arc_width( arc2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_arc_width( arc2, 15, LV_PART_MAIN );
    lv_obj_set_style_arc_color(arc2,lv_palette_darken( LV_PALETTE_LIGHT_GREEN,4),LV_PART_MAIN );
    lv_obj_set_style_arc_color(arc2,lv_color_hex(0x29a93e),LV_PART_INDICATOR );

    lv_arc_set_bg_angles(arc2, 0, 0);
   lv_arc_set_range(arc2, 0, 100);
    lv_arc_set_value(arc2, 0);
    lv_arc_set_rotation(arc2, 90);
    lv_obj_set_size(arc2, 180, 180);
    lv_obj_align(arc2, LV_ALIGN_CENTER, 0, 0);
    
     arc3 = lv_arc_create(ui_Screen1);
    lv_obj_set_style_arc_width( arc3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_arc_width( arc3, 15, LV_PART_MAIN );
    lv_obj_set_style_arc_color(arc3,lv_palette_darken( LV_PALETTE_PINK,4),LV_PART_MAIN );
    lv_obj_set_style_arc_color(arc3,lv_color_hex(0xdf3664),LV_PART_INDICATOR );
 lv_obj_remove_style(arc, NULL, LV_PART_KNOB);
 lv_obj_remove_style(arc2, NULL, LV_PART_KNOB);
 lv_obj_remove_style(arc3, NULL, LV_PART_KNOB);
    lv_arc_set_bg_angles(arc3, 0, 0);
   lv_arc_set_range(arc3, 0, 100);
    lv_arc_set_value(arc3, 0);
    lv_arc_set_rotation(arc3, 90);
    lv_obj_set_size(arc3, 140, 140);
    lv_obj_align(arc3, LV_ALIGN_CENTER, 0, 0);
    
    label1=lv_label_create(ui_Screen1);
    
lv_obj_set_style_text_font(label1, &lv_font_montserrat_40, 0);  
    lv_obj_set_width( label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height(label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( label1, 20 );
lv_obj_set_y(label1, -5 );
lv_obj_set_align( label1, LV_ALIGN_CENTER );
lv_label_set_text(label1, LV_SYMBOL_AUDIO "123");

label2=lv_label_create(ui_Screen1);
    
lv_obj_set_style_text_font(label2, &lv_font_montserrat_12, 0); 
lv_obj_set_style_text_color(label2, lv_color_hex(0x29a93e), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_width( label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height(label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( label2, 27 );
lv_obj_set_y(label2,83 );
lv_obj_set_align(label2, LV_ALIGN_CENTER );
lv_label_set_text(label2, LV_SYMBOL_BATTERY_3 );
//lv_label_set_text(label1,"00");
    mainPage_anim_line_init();

label3=lv_label_create(ui_Screen1);
    
lv_obj_set_style_text_font(label3, &lv_font_montserrat_12, 0); 
lv_obj_set_style_text_color(label3, lv_color_hex(0x29a93e), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_width( label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height(label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( label3, 27 );
lv_obj_set_y(label3,-83 );
lv_obj_set_align(label3, LV_ALIGN_CENTER );
lv_label_set_text(label3, "70%" );
//lv_label_set_text(label1,"00");
    mainPage_anim_line_init();

}
void mainPage_anim_line_init(){
lv_anim_t start_arc1;
lv_anim_t start_arc2;
lv_anim_t start_arc3;
lv_anim_t start_arc4;
    lv_anim_t start_arc5;
lv_anim_t start_arc6;
 start_mainPage_anim_timeline = lv_anim_timeline_create();
    set_anim_init(&start_arc1,arc,600,set_arc_bg_angle,0,180,lv_anim_path_ease_in_out);
    set_anim_init(&start_arc2,arc,600,set_arc_angle,0,40,lv_anim_path_ease_in_out);
    set_anim_init(&start_arc3,arc2,600,set_arc_bg_angle,0,180,lv_anim_path_ease_in_out);
    set_anim_init(&start_arc4,arc2,600,set_arc_angle,0,70,lv_anim_path_ease_in_out);
     set_anim_init(&start_arc5,arc3,600,set_arc_bg_angle,0,180,lv_anim_path_ease_in_out);
    set_anim_init(&start_arc6,arc3,600,set_arc_angle,0,90,lv_anim_path_ease_in_out);
     lv_anim_timeline_add(start_mainPage_anim_timeline,1, &start_arc1);
    lv_anim_timeline_add(start_mainPage_anim_timeline, 1, &start_arc2);
     lv_anim_timeline_add(start_mainPage_anim_timeline,50, &start_arc3);
    lv_anim_timeline_add(start_mainPage_anim_timeline, 50, &start_arc4);
    lv_anim_timeline_add(start_mainPage_anim_timeline,100, &start_arc5);
    lv_anim_timeline_add(start_mainPage_anim_timeline, 100, &start_arc6);
    lv_anim_timeline_start(start_mainPage_anim_timeline);
    
	
    
    
}