// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project
#include "lvgl.h"
#include "startPage.h"

#include "../lvgl_anim/lvgl_anim.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_TITLE;
lv_obj_t *ui_Label2;
lv_obj_t *ui____initial_actions0;


lv_anim_t start_title1;
lv_anim_t start_title2;
lv_anim_t start_bar;

lv_anim_t data_bar;
lv_anim_timeline_t* start_anim_timeline ;
lv_anim_timeline_t* end_anim_timeline ;
lv_timer_t * task1 = NULL;
///////////////////// TEST LVGL SETTINGS ////////////////////

///////////////////// ANIMATIONS ////////////////////

void set_anim_init(lv_anim_t* anim,lv_obj_t *TargetObject, int time,lv_anim_exec_xcb_t exec_cb,int16_t d_start,int16_t d_end,lv_anim_path_cb_t anim_path)
{    
    lv_anim_init(anim);
    lv_anim_set_var(anim,TargetObject);
    lv_anim_set_exec_cb(anim,exec_cb);
    lv_anim_set_repeat_count(anim, 0);
    lv_anim_set_values(anim, d_start, d_end);
    lv_anim_set_path_cb(anim, anim_path);
    lv_anim_set_time(anim, time);
    

    
}
void task1_cb(lv_timer_t * tmr)
{
	printf("finish\n");
    mainPage_init();
}

void ui_Screen1_screen_init(void)
{

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
    
    ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_obj_set_style_opa(ui_Bar1, 0, 0);
lv_bar_set_value(ui_Bar1,0,LV_ANIM_ON);
lv_obj_set_width( ui_Bar1, 150);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
ui_TITLE = lv_label_create(ui_Screen1);
lv_obj_set_style_opa(ui_TITLE, 0, 0);
lv_obj_set_width( ui_TITLE, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TITLE, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TITLE, -24 );
lv_obj_set_y( ui_TITLE, -14 );
lv_obj_set_align( ui_TITLE, LV_ALIGN_CENTER );
lv_label_set_text(ui_TITLE,"DESIGN BY");
ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_style_opa(ui_Label2, 0, 0);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 51 );
lv_obj_set_y( ui_Label2, -14 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ZYC");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x1B9CFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_disp_load_scr( ui_Screen1);
    lv_task_handler();
anim_line_init();


}
void anim_line_init(){
        set_anim_init(&data_bar,ui_Bar1,1000,anim_progress_load,0,100,lv_anim_path_ease_in_out);
    set_anim_init(&start_title1,ui_TITLE,500,set_opacity,1,254,lv_anim_path_ease_in_out);
    set_anim_init(&start_title2,ui_Label2,500,set_opacity,1,254,lv_anim_path_ease_in_out);
    set_anim_init(&start_bar,ui_Bar1,500,set_opacity,0,254,lv_anim_path_ease_in_out);

 lv_anim_set_playback_delay(&start_title1, 1300);
    lv_anim_set_playback_time(&start_title1, 500);
     lv_anim_set_playback_delay(&start_title2, 1300);
    lv_anim_set_playback_time(&start_title2, 500);
    lv_anim_set_playback_delay(&start_bar, 1300);
    lv_anim_set_playback_time(&start_bar, 500);
    start_anim_timeline = lv_anim_timeline_create();
    end_anim_timeline = lv_anim_timeline_create();

    lv_anim_timeline_add(start_anim_timeline, 800, &data_bar);

    lv_anim_timeline_add(start_anim_timeline,1, &start_title1);
    lv_anim_timeline_add(start_anim_timeline, 1, &start_title2);
    lv_anim_timeline_add(start_anim_timeline, 1, &start_bar);
   	lv_anim_timeline_start(start_anim_timeline);
       task1 = lv_timer_create(task1_cb, 2850, 0);
	lv_timer_set_repeat_count(task1,1);
    //lv_anim_timeline_start(end_anim_timeline);
    
	
    
    
}