// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _STARTPAGE_H
#define _STARTPAGE_H

#include "lvgl.h"
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_TITLE;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#endif
